### ISSUE TITLE
可以兼容steam版本吗

### ISSUE THREAD

**Issue by iamyou** [shinkuan/MajsoulUnlocker#1]
看样子steam版本估计有一段时间不会计划更新了

**Comment by shinkuan** [comment]
目前沒有計畫去兼容舊的版本。
這是因為舊版遲早會被升級到目前版本，去做兼容沒有太大的意義。

v0.10與v0.11的主要差別是在v0.10的一些method在v0.11被整合成了一個名為fetchInfo的method，而這也恰好是MITM攻擊的主要目標，因為很多資訊都在這個Method中被傳送。

如果你會一點Python的話可以嘗試自己做做看。

**Comment by shinkuan** [comment]
已更新對v10的支持。
https://github.com/shinkuan/MajsoulUnlocker/commit/93e11b906c0ac32f8b613fd2f8fb8e580ec2efe5

如果有問題請另開issue。
